---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: stagecentral
spec:
  owner: centrals
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-fastapi
spec:
  type: service
  lifecycle: experimental
  owner: centrals
  system: stagecentral
  providesApis: [central-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: central-api
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    openapi: 3.0.0
    info:
      version: 1.0.0
      title: Sample API
      description: A sample API to illustrate OpenAPI concepts
    paths:
      /list:
        get:
          description: Returns a list of stuff              
          responses:
            '200':
              description: Successful response
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: central
spec:
  memberOf: [centrals]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: centrals
spec:
  type: team
  children: []
